# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stl_sort <- function(x) {
    .Call('LAS_stl_sort', PACKAGE = 'LAS', x)
}

normalizeInput <- function(x) {
    invisible(.Call('LAS_normalizeInput', PACKAGE = 'LAS', x))
}

normalizeInputMatrix <- function(x) {
    invisible(.Call('LAS_normalizeInputMatrix', PACKAGE = 'LAS', x))
}

rcpp_hello_world <- function() {
    .Call('LAS_rcpp_hello_world', PACKAGE = 'LAS')
}

